version: '3.3'

services:

  nginx:
    image: bitnami/nginx:1.12
    volumes:
      - ./docker/templates/nginx/nginx.conf:/bitnami/nginx/conf/vhosts/nginx.conf:ro
    depends_on:
      - api
      - client
    environment:
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080

  api: &api_base
    build: .
    command: bundle exec puma -C config/puma.rb
    entrypoint: ./docker/entrypoints/api.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - bundle_cache:/bundle
      - .:/home/api
    env_file:
      - '.env'
    stdin_open: true
    tty: true

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'supersecret'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass supersecret
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *api_base
    entrypoint: './docker/entrypoints/sidekiq.sh'
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - redis

  client:
    build: ./client
    command: yarn start
    entrypoint: ./docker/entrypoints/client.sh
    volumes:
      - ./client:/home/client
    environment:
      NODE_ENV: development
    env_file:
      - '.env'

volumes:
  postgres:
  bundle_cache:
  redis:

