version: '3.3'

services:

  nginx:
    image: bitnami/nginx:1.12
    volumes:
      - ./docker/templates/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - api
      - client
    environment:
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080

  api: &api_base
    build: .
    command: bundle exec puma -C config/puma.rb
    entrypoint: ./docker/entrypoints/api.sh
    volumes:
      - bundle_cache:/bundle
      - .:/home/api
    depends_on:
      - redis
    env_file:
      - '.env'
    stdin_open: true
    tty: true

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass supersecret
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *api_base
    entrypoint: './docker/entrypoints/sidekiq.sh'
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - api

  client:
    build: ./client
    command: yarn start
    entrypoint: ./docker/entrypoints/client.sh
    depends_on:
      - api
    volumes:
      - ./client:/home/client
    environment:
      NODE_ENV: development
    env_file:
      - '.env'

volumes:
  bundle_cache:
  redis:
