# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_development
test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test
staging:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_staging
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_production
