fetch_tweets:
  class: FetchTweetsWorker
  every: '1m'
  description: 'Fetches and stores tweets from topics in the system'

prune_tweets:
  class: PruneTweetsWorker
  every: '2m'
  description: 'Prunes tweets that are not longer recent'
